version: '2'
services:
    clouddrop-app:
        image: clouddrop
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://clouddrop-mssql:1433;database=CloudDrop
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    clouddrop-mssql:
        extends:
            file: mssql.yml
            service: clouddrop-mssql
